version: "3.7"

networks:
  net-test:

services:
  influxdb:
    image: docker.io/influxdb:1.7
    container_name: influxdb
    hostname: influxdb
    environment:
      INFLUXDB_DB: tracing
    ports:
      - "8086:8086"
    networks:
      - net-test

  jaeger-all-in-one:
    build:
      context: .
      dockerfile: ./cmd/jaeger-influxdb/Dockerfile.all-in-one
    container_name: jaeger-all-in-one
    entrypoint: /go/bin/all-in-one-linux
    depends_on:
      - influxdb
    ports:
      - "16686:16686"
    networks:
      - net-test
